const app = document.querySelector('#app');
const homeTpl = document.querySelector('#homeTemplate');
const studioTpl = document.querySelector('#studioTemplate');
const STORAGE='smezi-brand-studio-v1';
const initial={name:'',site:'',segment:'',description:'',competitors:['','','','',''],references:['','',''],traits:['inteligente','contemporânea'],avoid:[],styles:['tech'],font:'manrope',palette:'digital',logo:'symbol',axes:[62,38,54,58,72]};
let state={...initial,...JSON.parse(localStorage.getItem(STORAGE)||'{}')};
let step=0;
const stepMeta=[
 ['Conhecendo o negócio','Qual é o nome da sua marca?'],
 ['Contexto & referências','Quem disputa a atenção do seu cliente?'],
 ['Briefing inteligente','Como sua marca deve ser percebida?'],
 ['Direção visual','Sem termos técnicos. Só: “gosto disso”.'],
 ['Visual Board','Agora vamos montar a identidade.'],
 ['Síntese','Entendi sua marca assim.']
];
const palettes={digital:['#0a0a0b','#725cff','#43e6ff','#ccff00'],warm:['#201b17','#c37053','#e8c79f','#f7efe6'],premium:['#0d1825','#b89a5c','#e7dfd0','#ffffff'],bold:['#ff4d00','#ff6ee7','#151515','#f5f0e8']};
const traits=['inteligente','sofisticada','humana','inovadora','forte','acessível','técnica','premium','minimalista','ousada','contemporânea','criativa'];
const avoid=['genérica','infantil','startup clichê','antiga','artificial','fria','exageradamente luxuosa','confusa','corporativa demais'];

function save(){localStorage.setItem(STORAGE,JSON.stringify(state)); updatePreview();}
function escapeHTML(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showHome(){app.innerHTML='';app.append(homeTpl.content.cloneNode(true));document.querySelectorAll('[data-action="brand"]').forEach(b=>b.onclick=showStudio);}
function showStudio(){app.innerHTML='';app.append(studioTpl.content.cloneNode(true));document.querySelector('#railHome').onclick=showHome;document.querySelector('#backBtn').onclick=()=>{if(step===0)return showHome();step--;renderStep();};document.querySelector('#nextBtn').onclick=()=>{if(step<5){step++;renderStep();}else alert('Brand Brain salvo. Próximo passo: gerar a identidade completa.');};document.querySelectorAll('.rail-step').forEach(b=>b.onclick=()=>{step=+b.dataset.step;renderStep();});renderStep();}
function renderStep(){const [eye,title]=stepMeta[step];document.querySelector('#stepEyebrow').textContent=eye;document.querySelector('#stepTitle').textContent=title;document.querySelector('#stepCurrent').textContent=String(step+1).padStart(2,'0');const body=document.querySelector('#stageBody');body.innerHTML='';if(step===0)renderBusiness(body);if(step===1)renderRefs(body);if(step===2)renderPersonality(body);if(step===3)renderVisualDirections(body);if(step===4)renderBoard(body);if(step===5)renderSummary(body);document.querySelector('#backBtn').textContent=step===0?'← início':'← voltar';document.querySelector('#nextBtn').innerHTML=step===5?'criar minha identidade <span>✦</span>':'continuar <span>→</span>';document.querySelectorAll('.rail-step').forEach((b,i)=>{b.classList.toggle('active',i===step);b.classList.toggle('done',i<step)});document.querySelector('#railProgress').style.height=`${Math.min(step/5*88,88)}%`;const pct=Math.min(14+step*15+(state.name?5:0),96);document.querySelector('#brainPercent').textContent=pct+'%';document.querySelector('#brainBar').style.width=pct+'%';updatePreview();body.animate([{opacity:.2,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:260,easing:'ease-out'});}
function inputField(label,key,placeholder,type='text'){return `<div class="field"><label>${label}</label><input type="${type}" data-key="${key}" value="${escapeHTML(state[key]||'')}" placeholder="${placeholder}"></div>`}
function renderBusiness(el){el.innerHTML=`<div class="field-stack">${inputField('NOME DA MARCA / NEGÓCIO','name','ex.: SMEZI')}${inputField('SITE — SE EXISTIR','site','https://')}${inputField('SEGMENTO','segment','ex.: tecnologia, saúde, financeiro...')}<div class="field"><label>EM UMA FRASE, O QUE VOCÊ FAZ? <span style="font-weight:400">(opcional)</span></label><textarea data-key="description" placeholder="Sem texto perfeito. Escreva como você explicaria para alguém.">${escapeHTML(state.description||'')}</textarea></div><p class="micro-note">✦ Eu uso essas respostas apenas como ponto de partida. A marca vai ficando mais precisa conforme você avança.</p></div>`;bindInputs(el);document.querySelector('#footerNote').textContent='Pode mudar tudo depois.';}
function renderRefs(el){el.innerHTML=`<p class="micro-note">Adicione até 5 links. Concorrente é quem disputa o mesmo cliente — referência é quem você admira, mesmo que venda outra coisa.</p><h4 class="subhead">Concorrentes</h4><div class="link-list" id="competitors">${state.competitors.map((v,i)=>`<div class="link-row"><input data-list="competitors" data-index="${i}" value="${escapeHTML(v)}" placeholder="site, Instagram ou outra referência"><button>↗</button></div>`).join('')}</div><button class="find-btn">✦ Não sei meus concorrentes — encontrar para mim</button><h4 class="subhead">Marcas que você admira</h4><div class="link-list">${state.references.map((v,i)=>`<div class="link-row"><input data-list="references" data-index="${i}" value="${escapeHTML(v)}" placeholder="link, site ou perfil"><button>＋</button></div>`).join('')}</div>`;bindListInputs(el);document.querySelector('#footerNote').textContent='Concorrentes ≠ referências.';}
function tagHTML(x,key){return `<button class="choice ${state[key].includes(x)?'selected':''}" data-tag="${key}" data-value="${x}">${x}</button>`}
function renderPersonality(el){el.innerHTML=`<p class="micro-note">Escolha quantas quiser. Não procure a resposta certa — procure o que parece verdadeiro.</p><h4 class="subhead">Quero que minha marca pareça...</h4><div class="choice-grid">${traits.map(x=>tagHTML(x,'traits')).join('')}<button class="choice">＋ outro</button></div><h4 class="subhead">E definitivamente NÃO pareça...</h4><div class="choice-grid">${avoid.map(x=>tagHTML(x,'avoid')).join('')}<button class="choice">＋ outro</button></div>`;bindTags(el);document.querySelector('#footerNote').textContent='Seleção múltipla liberada.';}
function renderVisualDirections(el){const styles=[['editorial','Editorial','ritmo, contraste e personalidade'],['minimal','Minimalista','silêncio visual e precisão'],['tech','Tech','digital, fluido e inteligente'],['organic','Orgânico','formas naturais e proximidade'],['premium','Premium','luxo discreto e confiança'],['bold','Expressivo','energia e presença']];el.innerHTML=`<p class="micro-note">Você não precisa saber o nome do estilo. Olhe e escolha o que te atrai.</p><div class="visual-options">${styles.map(([k,n,d])=>`<button class="visual-option ${state.styles.includes(k)?'selected':''}" data-style="${k}"><div class="style-art ${k}"></div><div><strong>${n}</strong><p>${d}</p></div></button>`).join('')}</div>`;el.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{const v=b.dataset.style;if(state.styles.includes(v))state.styles=state.styles.filter(x=>x!==v);else state.styles.push(v);save();renderVisualDirections(el);});document.querySelector('#footerNote').textContent='Gosto disso. É suficiente.';}
function renderBoard(el){const p=(id,cols)=>`<button class="palette ${state.palette===id?'selected':''}" data-palette="${id}">${cols.map(c=>`<i style="background:${c}"></i>`).join('')}</button>`;el.innerHTML=`<div class="board-controls"><section class="board-section"><h4>TIPOGRAFIA <span style="color:#999;font-weight:400">— aplicada, não em lista</span></h4><div class="font-options"><button class="font-chip ${state.font==='manrope'?'selected':''}" data-font="manrope"><strong style="font-family:Manrope">Aa</strong><span>Manrope / limpa</span></button><button class="font-chip ${state.font==='playfair'?'selected':''}" data-font="playfair"><strong style="font-family:'Playfair Display'">Aa</strong><span>Playfair / editorial</span></button><button class="font-chip ${state.font==='dm'?'selected':''}" data-font="dm"><strong style="font-family:'DM Sans'">Aa</strong><span>DM Sans / direta</span></button></div></section><section class="board-section"><h4>PALETA</h4><div class="palette-options">${Object.entries(palettes).map(([id,cols])=>p(id,cols)).join('')}</div></section><section class="board-section"><h4>LOGO — CAMINHO CONCEITUAL</h4><div class="logo-options"><button class="logo-choice ${state.logo==='wordmark'?'selected':''}" data-logo="wordmark">WORDMARK · SMEZI</button><button class="logo-choice ${state.logo==='symbol'?'selected':''}" data-logo="symbol">▣ + SMEZI</button><button class="logo-choice ${state.logo==='mono'?'selected':''}" data-logo="mono">MONOGRAMA · S</button></div></section><section class="board-section"><h4>DIREÇÃO DE IMAGEM</h4><p class="micro-note">Luz real, enquadramentos com intenção, textura digital sutil e nada de banco de imagem genérico.</p><button class="find-btn">mostrar outras parecidas ↻</button></section></div>`;el.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{state.font=b.dataset.font;save();renderBoard(el)});el.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>{state.palette=b.dataset.palette;save();renderBoard(el)});el.querySelectorAll('[data-logo]').forEach(b=>b.onclick=()=>{state.logo=b.dataset.logo;save();renderBoard(el)});document.querySelector('#footerNote').textContent='Misture caminhos. Nada é definitivo.';}
function renderSummary(el){const t=state.traits.slice(0,6);el.innerHTML=`<div class="summary-card"><div class="summary-top"><div><span class="eyebrow" style="color:#8f8f95">BRAND BRAIN · SÍNTESE</span><h3>${escapeHTML(state.name||'Sua marca')}</h3></div><div class="brain-ring"><span>92</span></div></div><p class="micro-note" style="color:#a8a8ae">Uma marca ${escapeHTML((state.traits||[]).slice(0,3).join(', ')||'clara e contemporânea')}, com direção visual ${escapeHTML((state.styles||[]).join(' + ')||'própria')} e linguagem sem ruído.</p><div class="summary-tags">${t.map(x=>`<span>${x}</span>`).join('')} ${(state.avoid||[]).slice(0,3).map(x=>`<span>não: ${x}</span>`).join('')}</div><div class="axis-list">${[['Institucional','Experimental'],['Minimalista','Expressiva'],['Humana','Técnica'],['Acessível','Premium'],['Clássica','Contemporânea']].map((a,i)=>`<label class="axis"><span>${a[0]}</span><input type="range" min="0" max="100" value="${state.axes[i]}" data-axis="${i}"><span>${a[1]}</span></label>`).join('')}</div><div class="final-cta"><button class="primary">✦ Criar minha identidade</button><button>ajustar escolhas</button></div></div>`;el.querySelectorAll('[data-axis]').forEach(r=>r.oninput=()=>{state.axes[+r.dataset.axis]=+r.value;save()});document.querySelector('#footerNote').textContent='Você continua no controle.';}
function bindInputs(el){el.querySelectorAll('[data-key]').forEach(i=>i.addEventListener('input',()=>{state[i.dataset.key]=i.value;save()}));}
function bindListInputs(el){el.querySelectorAll('[data-list]').forEach(i=>i.addEventListener('input',()=>{state[i.dataset.list][+i.dataset.index]=i.value;save()}));}
function bindTags(el){el.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{const k=b.dataset.tag,v=b.dataset.value;state[k]=state[k].includes(v)?state[k].filter(x=>x!==v):[...state[k],v];save();renderPersonality(el)});}
function updatePreview(){const live=document.querySelector('#brandPreview');if(!live)return;const name=(state.name||'SUA MARCA').toUpperCase();document.querySelector('#previewName').textContent=name;document.querySelector('#previewSymbol').textContent=(state.name||'S').charAt(0).toUpperCase();document.querySelector('#previewMood').textContent=(state.traits||[]).slice(0,3).join(' / ')||'inteligente / contemporânea';document.querySelector('#previewHeadline').textContent=state.name?`${state.name}: uma identidade que já começa a parecer sua.`:'Uma identidade que começa a tomar forma.';const pal=palettes[state.palette]||palettes.digital;document.querySelectorAll('#paletteCard i').forEach((x,i)=>x.style.background=pal[i]);document.querySelector('#brandPreview').style.setProperty('--accent',pal[1]);const glow=document.querySelector('.preview-glow');glow.style.background=`radial-gradient(circle at 35% 35%,${pal[2]},transparent 52%),radial-gradient(circle at 65% 65%,${pal[1]},transparent 58%)`;const ts=document.querySelector('#typeSample');ts.style.fontFamily=state.font==='playfair'?"'Playfair Display'":state.font==='dm'?"'DM Sans'":"Manrope";const h=document.querySelector('#previewHeadline');h.style.fontFamily=state.font==='playfair'?"'Playfair Display'":state.font==='dm'?"'DM Sans'":"Manrope";document.querySelector('#photoCard').style.background=state.styles.includes('premium')?'linear-gradient(135deg,#17130f,#6b5a3b)':state.styles.includes('organic')?'linear-gradient(135deg,#a8bc83,#be765f)':'linear-gradient(135deg,#7d8fa7,#1f2834)';document.querySelector('#insightText').textContent=state.name?`Já entendi ${state.name} como ${state.traits.slice(0,3).join(', ')||'uma marca em construção'}. Continue: eu ajusto a direção a cada escolha.`:'Comece pelo nome. Eu vou conectando os pontos enquanto você escolhe.';live.classList.remove('pulse');void live.offsetWidth;live.classList.add('pulse');}

document.querySelector('#homeBtn').onclick=showHome;
showHome();